Update circle.yml

diff --git a/circle.yml b/circle.yml
--- a/circle.yml
+++ b/circle.yml
@@ -1,12 +1,43 @@
-machine:
-  ruby:
-    version: 2.4.3
+#!/bin/bash
 
-dependencies:
-  pre:
-    - ./bin/setup
+# Automated deploy script with Circle CI.
 
-test:
-  post:
-    - bundle exec jekyll build
-    - bundle exec htmlproofer ./_site --only-4xx --allow-hash-href --assume-extension --check-opengraph
+# Exit if any subcommand fails.
+set -e
+
+# Variables
+ORIGIN_URL=`git config --get remote.origin.url`
+
+echo "Started deploying"
+
+# Checkout gh-pages branch.
+if [ `git branch | grep gh-pages` ]
+then
+  git branch -D gh-pages
+fi
+git checkout -b gh-pages
+
+# Build site.
+yarn install --modules-folder ./_assets/yarn
+bundle exec jekyll build
+
+# Delete and move files.
+find . -maxdepth 1 ! -name '_site' ! -name '.git' ! -name '.gitignore' -exec rm -rf {} \;
+mv _site/* .
+rm -R _site/
+
+# Push to gh-pages.
+git config user.name "madkeen"
+git config user.email "me@keenanadams.net"
+
+git add -fA
+git commit --allow-empty -m "$(git log -1 --pretty=%B) [ci skip]"
+git push -f $ORIGIN_URL gh-pages
+
+# Move back to previous branch.
+git checkout -
+yarn install --modules-folder ./_assets/yarn
+
+echo "Deployed Successfully!"
+
+exit 0
